[env:blackpill_f401cc]
platform = ststm32
board = blackpill_f401cc
framework = arduino
build_flags = 
    -DUSBCON
    -DUSBD_USE_CDC
    -DHAL_PCD_MODULE_ENABLED
upload_protocol = dfu
monitor_speed = 115200