[platformio]

src_dir = .
include_dir = Core/Inc
[env:genericSTM32F401CC]
platform = ststm32

board = genericSTM32F401CC
framework = stm32cube

board_build.stm32cube.custom_config_header = yes
; Tambahkan folder include tambahan yang tertera di Makefile
build_flags = 
    -I Core/Inc
    -I USB_DEVICE/App
    -I USB_DEVICE/Target

build_src_filter = 
    +<Core/Src/*.c>
    -<Core/Src/hexapod.c>
    -<Core/Src/usb_stubs.c>
    +<startup_stm32f401xc.s>
    +<USB_DEVICE/App/*.c>
    +<USB_DEVICE/Target/*.c>